// ─── Dummy Data for SkillMatch.lk ────────────────────────────────────────────
// Used for UI development and demonstration purposes

import type { WorkerProfile, Gig, Review, User } from '@/types';

export const dummyUsers: User[] = [
    {
        _id: 'u1',
        name: 'Kasun Perera',
        email: 'kasun@example.com',
        role: 'worker',
        profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kasun&backgroundColor=b6e3f4',
        isVerified: true,
        status: 'active',
        createdAt: '2024-01-15T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
    },
    {
        _id: 'u2',
        name: 'Nimasha Silva',
        email: 'nimasha@example.com',
        role: 'worker',
        profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nimasha&backgroundColor=ffdfbf',
        isVerified: true,
        status: 'active',
        createdAt: '2024-02-10T00:00:00Z',
        updatedAt: '2024-02-10T00:00:00Z',
    },
    {
        _id: 'u3',
        name: 'Tharindu Fernando',
        email: 'tharindu@example.com',
        role: 'worker',
        profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tharindu&backgroundColor=c0aede',
        isVerified: true,
        status: 'active',
        createdAt: '2024-01-20T00:00:00Z',
        updatedAt: '2024-01-20T00:00:00Z',
    },
    {
        _id: 'u4',
        name: 'Dilani Jayawardena',
        email: 'dilani@example.com',
        role: 'worker',
        profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dilani&backgroundColor=d1d4f9',
        isVerified: false,
        status: 'active',
        createdAt: '2024-03-05T00:00:00Z',
        updatedAt: '2024-03-05T00:00:00Z',
    },
    {
        _id: 'u5',
        name: 'Ruwan Bandara',
        email: 'ruwan@example.com',
        role: 'worker',
        profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ruwan&backgroundColor=ffd5dc',
        isVerified: true,
        status: 'active',
        createdAt: '2024-02-28T00:00:00Z',
        updatedAt: '2024-02-28T00:00:00Z',
    },
    {
        _id: 'u6',
        name: 'Sachini Wickramasinghe',
        email: 'sachini@example.com',
        role: 'worker',
        profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sachini&backgroundColor=b6e3f4',
        isVerified: true,
        status: 'active',
        createdAt: '2024-03-12T00:00:00Z',
        updatedAt: '2024-03-12T00:00:00Z',
    },
];

export const dummyWorkers: WorkerProfile[] = [
    {
        _id: 'wp1',
        userId: dummyUsers[0],
        bio: 'Full-stack developer with 5+ years of experience building scalable web applications. Specialized in React, Node.js, and cloud architecture.',
        skills: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'AWS'],
        experience: 5,
        location: { city: 'Colombo', district: 'Colombo', province: 'Western' },
        hourlyRate: 3500,
        availability: 'available',
        certifications: ['AWS Certified Developer', 'Google Cloud Professional'],
        portfolio: [
            'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400',
            'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400',
        ],
        category: 'Web Development',
        averageRating: 4.9,
        totalReviews: 47,
        completedJobs: 63,
        isVerified: true,
        totalEarnings: 220500,
        createdAt: '2024-01-15T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
    },
    {
        _id: 'wp2',
        userId: dummyUsers[1],
        bio: 'Creative UI/UX designer and brand identity specialist. I craft beautiful, user-centered designs that convert visitors into customers.',
        skills: ['Figma', 'Adobe XD', 'Illustrator', 'Photoshop', 'Branding'],
        experience: 4,
        location: { city: 'Kandy', district: 'Kandy', province: 'Central' },
        hourlyRate: 2800,
        availability: 'available',
        certifications: ['Google UX Design Certificate'],
        portfolio: [
            'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400',
            'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=400',
        ],
        category: 'Graphic Design',
        averageRating: 4.8,
        totalReviews: 32,
        completedJobs: 41,
        isVerified: true,
        totalEarnings: 114800,
        createdAt: '2024-02-10T00:00:00Z',
        updatedAt: '2024-02-10T00:00:00Z',
    },
    {
        _id: 'wp3',
        userId: dummyUsers[2],
        bio: 'Licensed electrician with 8 years of residential and commercial experience. Fast, reliable, and safety-first approach to every job.',
        skills: ['Wiring', 'Panel Upgrades', 'Solar Installation', 'CCTV', 'Troubleshooting'],
        experience: 8,
        location: { city: 'Gampaha', district: 'Gampaha', province: 'Western' },
        hourlyRate: 1800,
        availability: 'busy',
        certifications: ['Licensed Electrician - SLTB', 'Solar PV Installer'],
        portfolio: [
            'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400',
        ],
        category: 'Electrical',
        averageRating: 4.7,
        totalReviews: 89,
        completedJobs: 124,
        isVerified: true,
        totalEarnings: 223200,
        createdAt: '2024-01-20T00:00:00Z',
        updatedAt: '2024-01-20T00:00:00Z',
    },
    {
        _id: 'wp4',
        userId: dummyUsers[3],
        bio: 'Digital marketing expert specializing in SEO, social media growth, and paid advertising. Helped 30+ businesses grow their online presence.',
        skills: ['SEO', 'Google Ads', 'Facebook Ads', 'Content Marketing', 'Analytics'],
        experience: 3,
        location: { city: 'Negombo', district: 'Gampaha', province: 'Western' },
        hourlyRate: 2200,
        availability: 'available',
        certifications: ['Google Ads Certified', 'HubSpot Content Marketing'],
        portfolio: [],
        category: 'Digital Marketing',
        averageRating: 4.6,
        totalReviews: 21,
        completedJobs: 28,
        isVerified: false,
        totalEarnings: 61600,
        createdAt: '2024-03-05T00:00:00Z',
        updatedAt: '2024-03-05T00:00:00Z',
    },
    {
        _id: 'wp5',
        userId: dummyUsers[4],
        bio: 'Professional plumber with expertise in residential repairs, bathroom renovations, and pipe installations. Available 24/7 for emergencies.',
        skills: ['Pipe Fitting', 'Bathroom Renovation', 'Water Heaters', 'Leak Repair', 'Drainage'],
        experience: 10,
        location: { city: 'Matara', district: 'Matara', province: 'Southern' },
        hourlyRate: 1500,
        availability: 'available',
        certifications: ['Certified Plumber - TVEC'],
        portfolio: [
            'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400',
        ],
        category: 'Plumbing',
        averageRating: 4.8,
        totalReviews: 156,
        completedJobs: 203,
        isVerified: true,
        totalEarnings: 304500,
        createdAt: '2024-02-28T00:00:00Z',
        updatedAt: '2024-02-28T00:00:00Z',
    },
    {
        _id: 'wp6',
        userId: dummyUsers[5],
        bio: 'Professional photographer specializing in weddings, corporate events, and product photography. Delivering stunning visuals that tell your story.',
        skills: ['Wedding Photography', 'Portrait', 'Product Photography', 'Photo Editing', 'Videography'],
        experience: 6,
        location: { city: 'Colombo', district: 'Colombo', province: 'Western' },
        hourlyRate: 4500,
        availability: 'available',
        certifications: ['Adobe Certified Expert'],
        portfolio: [
            'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400',
            'https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=400',
        ],
        category: 'Photography',
        averageRating: 5.0,
        totalReviews: 38,
        completedJobs: 52,
        isVerified: true,
        totalEarnings: 234000,
        createdAt: '2024-03-12T00:00:00Z',
        updatedAt: '2024-03-12T00:00:00Z',
    },
];

export const dummyGigs: Gig[] = [
    {
        _id: 'g1',
        workerId: dummyUsers[0],
        title: 'I will build a full-stack web application with React and Node.js',
        description: 'Professional full-stack development using React, Node.js, MongoDB. Includes responsive design, authentication, and deployment.',
        category: 'Web Development',
        price: 25000,
        images: ['https://images.unsplash.com/photo-1547658719-da2b51169166?w=600'],
        deliveryTime: 14,
        deliveryUnit: 'days',
        locationType: 'island-wide',
        isActive: true,
        tags: ['React', 'Node.js', 'Full Stack', 'MongoDB'],
        totalOrders: 23,
        views: 1240,
        createdAt: '2024-01-15T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
    },
    {
        _id: 'g2',
        workerId: dummyUsers[1],
        title: 'I will design a stunning UI/UX for your mobile or web app',
        description: 'Complete UI/UX design with wireframes, prototypes, and final Figma files. Modern, clean, and user-friendly designs.',
        category: 'Graphic Design',
        price: 15000,
        images: ['https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600'],
        deliveryTime: 7,
        deliveryUnit: 'days',
        locationType: 'island-wide',
        isActive: true,
        tags: ['UI Design', 'UX', 'Figma', 'Mobile App'],
        totalOrders: 18,
        views: 890,
        createdAt: '2024-02-10T00:00:00Z',
        updatedAt: '2024-02-10T00:00:00Z',
    },
    {
        _id: 'g3',
        workerId: dummyUsers[3],
        title: 'I will manage your social media and grow your audience',
        description: 'Complete social media management including content creation, scheduling, engagement, and monthly analytics reports.',
        category: 'Digital Marketing',
        price: 18000,
        images: ['https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600'],
        deliveryTime: 30,
        deliveryUnit: 'days',
        locationType: 'island-wide',
        isActive: true,
        tags: ['Social Media', 'Instagram', 'Facebook', 'Content'],
        totalOrders: 12,
        views: 654,
        createdAt: '2024-03-05T00:00:00Z',
        updatedAt: '2024-03-05T00:00:00Z',
    },
    {
        _id: 'g4',
        workerId: dummyUsers[5],
        title: 'I will photograph your wedding or corporate event professionally',
        description: 'Full-day event photography with 300+ edited photos delivered within 7 days. Includes online gallery and USB drive.',
        category: 'Photography',
        price: 45000,
        images: ['https://images.unsplash.com/photo-1519741497674-611481863552?w=600'],
        deliveryTime: 7,
        deliveryUnit: 'days',
        locationType: 'island-wide',
        isActive: true,
        tags: ['Wedding', 'Events', 'Photography', 'Editing'],
        totalOrders: 31,
        views: 2100,
        createdAt: '2024-03-12T00:00:00Z',
        updatedAt: '2024-03-12T00:00:00Z',
    },
    {
        _id: 'g5',
        workerId: dummyUsers[0],
        title: 'I will create a professional e-commerce store with Next.js',
        description: 'Full e-commerce solution with product management, cart, checkout, payment integration, and admin dashboard.',
        category: 'Web Development',
        price: 40000,
        images: ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600'],
        deliveryTime: 21,
        deliveryUnit: 'days',
        locationType: 'island-wide',
        isActive: true,
        tags: ['E-commerce', 'Next.js', 'Stripe', 'Admin'],
        totalOrders: 9,
        views: 780,
        createdAt: '2024-02-01T00:00:00Z',
        updatedAt: '2024-02-01T00:00:00Z',
    },
    {
        _id: 'g6',
        workerId: dummyUsers[1],
        title: 'I will create a complete brand identity with logo and guidelines',
        description: 'Professional brand identity including logo design, color palette, typography, business card, and brand guidelines PDF.',
        category: 'Graphic Design',
        price: 20000,
        images: ['https://images.unsplash.com/photo-1634942537034-2531766767d1?w=600'],
        deliveryTime: 10,
        deliveryUnit: 'days',
        locationType: 'island-wide',
        isActive: true,
        tags: ['Logo', 'Branding', 'Identity', 'Design'],
        totalOrders: 27,
        views: 1560,
        createdAt: '2024-02-15T00:00:00Z',
        updatedAt: '2024-02-15T00:00:00Z',
    },
];

export const dummyReviews: Review[] = [
    {
        _id: 'r1',
        customerId: { _id: 'c1', name: 'Amara Dissanayake', email: 'amara@example.com', role: 'customer', profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amara', isVerified: true, status: 'active', createdAt: '', updatedAt: '' },
        workerId: dummyUsers[0],
        jobId: 'j1',
        rating: 5,
        comment: 'Kasun delivered an exceptional web application. His code quality is outstanding and he communicated perfectly throughout the project. Highly recommended!',
        isVisible: true,
        createdAt: '2024-03-01T00:00:00Z',
        updatedAt: '2024-03-01T00:00:00Z',
    },
    {
        _id: 'r2',
        customerId: { _id: 'c2', name: 'Priya Ratnayake', email: 'priya@example.com', role: 'customer', profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya', isVerified: true, status: 'active', createdAt: '', updatedAt: '' },
        workerId: dummyUsers[1],
        jobId: 'j2',
        rating: 5,
        comment: 'Nimasha created a beautiful design for our app. She understood our vision perfectly and delivered beyond expectations. Will definitely work with her again!',
        isVisible: true,
        createdAt: '2024-03-05T00:00:00Z',
        updatedAt: '2024-03-05T00:00:00Z',
    },
    {
        _id: 'r3',
        customerId: { _id: 'c3', name: 'Saman Kumara', email: 'saman@example.com', role: 'customer', profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Saman', isVerified: true, status: 'active', createdAt: '', updatedAt: '' },
        workerId: dummyUsers[4],
        jobId: 'j3',
        rating: 5,
        comment: 'Ruwan fixed our plumbing issue quickly and professionally. He arrived on time, explained everything clearly, and the price was very reasonable. 5 stars!',
        isVisible: true,
        createdAt: '2024-03-10T00:00:00Z',
        updatedAt: '2024-03-10T00:00:00Z',
    },
];

export const dummyCategories = [
    { name: 'Web Development', icon: '💻', count: 124, color: 'from-blue-500 to-cyan-500' },
    { name: 'Graphic Design', icon: '🎨', count: 89, color: 'from-pink-500 to-rose-500' },
    { name: 'Digital Marketing', icon: '📱', count: 67, color: 'from-orange-500 to-amber-500' },
    { name: 'Plumbing', icon: '🔧', count: 52, color: 'from-teal-500 to-green-500' },
    { name: 'Electrical', icon: '⚡', count: 58, color: 'from-yellow-500 to-orange-500' },
    { name: 'Photography', icon: '📷', count: 43, color: 'from-purple-500 to-violet-500' },
    { name: 'Tutoring', icon: '📚', count: 76, color: 'from-indigo-500 to-blue-500' },
    { name: 'Cleaning', icon: '🧹', count: 95, color: 'from-green-500 to-emerald-500' },
    { name: 'Carpentry', icon: '🪚', count: 38, color: 'from-amber-600 to-yellow-600' },
    { name: 'Cooking', icon: '👨‍🍳', count: 29, color: 'from-red-500 to-orange-500' },
    { name: 'Content Writing', icon: '✍️', count: 61, color: 'from-sky-500 to-blue-500' },
    { name: 'Video Editing', icon: '🎬', count: 44, color: 'from-violet-500 to-purple-500' },
];

export const dummyStats = [
    { value: '12,400+', label: 'Skilled Workers', icon: '👷' },
    { value: '58,000+', label: 'Jobs Completed', icon: '✅' },
    { value: '25+', label: 'Categories', icon: '📂' },
    { value: '4.8★', label: 'Average Rating', icon: '⭐' },
];
